package:
    name: gorgon-hello
    version: 0.1

build:
    number: 1
    features:
        - vc9    # [win and py27]
        - vc10   # [win and py34]
        - vc14   # [win and py35]
  
source:
    git_url: https://github.com/GorgonCryoEM/gorgon-hello.git
    git_tag: master

requirements:
    build:
        - cmake >=3.4
        - python
        - boost
        - setuptools
    run:
        - python
        - boost

test:
    requires:
        - python {{ environ['PY_VER'] + '*' }}  # [win]
        - cmake
        - nose
    commands:
        - nosetests --with-doctest --doctest-tests -vv
 
about:
  summary: Gorgon 'Hello World!'
