travis:
  secure:
    BINSTAR_TOKEN: ePXo0z8S3NPREBEbwdOPLAcwD3GAtJp1xwbJkzFRbnO/nCQPUC9/9VdBCaWtiaD5wlMSbXiwaEZdM65l4vExUlPxcaR7hVQEfX2i9skNCxQkT2GfYNbUqUVO5CspWU3gYDyAQqvapNPot40ta0b2eoH3tmraXIJ1g0SjODM74Kpv/iP7ynr0SJqZwCnVs6d7yfhiAC14NQdLv6BfJlFjOqMDTqf3T9irCT9TCZG1bq+9ZJ83jZVe1PVS8s9oCJXzhVCqeNLv3yEDymwfQRUQvh24cRgmbn4x7G7zIFEqHBaTP8Bn9/CcLnfXcuTtPupfZjxMuHz6+hdpa8JZDsUh1dTK2bFCOnVXHAo2KW9rboEEplL2yLyyCoUai2yXbS32EXXt1C2L2EYN9xzCMf41IPwBEXPjIGTIk2BSWSb8JklqFEg4lRfQQSRBis7OmG0naZn6PpDoVtF9kdgnTVi2IE20xq+aVZWiFY+523l1mZR5QSThJicHOp9rKyKmGSLJoj5DFjE+WNcll81QTDutw+8zek2pBFnlHv+uTCxSvZVQ9NlWaFHKro8Tqkvr2ZCvPvLNXWpt2BaimD40qBcXzAvsT4nY5T/jkAiorw17gIaCzEXpeq5sUNs8+sYWkzrB4QZM2ek2QHPfTh+LqnnX/F08onLDX+fxqXGeefPEGl8=
appveyor:
  secure:
    BINSTAR_TOKEN: 4ef5IUakGqqw7GSfuIp93Q4MdAC1VnweE1kFVAOUs6ThPDQWBqNpGaq6ZuEbX1FL

channels:
  targets:
  - [gorgoncryoem, main]

github:
  user_or_org: gorgoncryoem
  repo_name: gorgon-hello-feedstock
